name: Test

# Controls when the action will run.
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

jobs:
  # make a new version first, release or prerelease
  test:
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git user
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Basic testing
        shell: sh
        run: |
          set -x
          rm -Rf my-test-project
          cookiecutter --no-input .
          cd my-test-project
          # add a git repo which some checks expect
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git init -b main && git add -A && git commit --no-sign -m "Initial."
          # remove the link check which will not work here
          sed -i -e '/sphinx-build -b linkcheck/d' tox.ini
          tox
